[project]
name = "power-pack"
version = "0.1.0"
description = "Data measurement for PowerPack project"
readme = "README.md"
authors = [{ name = "Matthew Amend" }, { name = "Rhea Parekh" }]
requires-python = ">=3.9"
dependencies = [
    "h5py>=3.14.0",
    "matplotlib>=3.9.4",
    "nidaqmx==1.0.1",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
]

[project.scripts]
power-pack = "power_pack.__main__:main"

[dependency-groups]
dev = ["pytest>=8.4.2", "ruff>=0.16.8"]

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
markers = ["nidaq: tests that require an NI-DAQ device"]
